type MockGradleProperty = {
  type: string;
  key?: string;
  value?: string;
};

const mockAppliedGradleProperties: MockGradleProperty[][] = [];

jest.mock('expo/config-plugins', () => ({
  withGradleProperties: (
    config: unknown,
    action: (gradleConfig: { modResults: MockGradleProperty[] }) => unknown
  ) => {
    const gradlePropertyBatches: MockGradleProperty[][] = [
      [
        { type: 'property', key: 'kotlinVersion', value: '1.9.24' },
        { type: 'property', key: 'otherProperty', value: 'keep-me' },
      ],
      [{ type: 'comment', value: '# generated by plugin' }],
    ];

    for (const batch of gradlePropertyBatches) {
      const gradleConfig = {
        modResults: batch.map((item) => ({ ...item })),
      };

      action(gradleConfig);
      mockAppliedGradleProperties.push(gradleConfig.modResults.map((item) => ({ ...item })));
    }

    return config;
  },
}));

function loadExpoConfig() {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const configModule = require('../../app.config') as {
    default: () => { name?: string; extra?: unknown };
  };

  return configModule.default;
}

describe('getExpoConfig', () => {
  beforeEach(() => {
    jest.resetModules();
    mockAppliedGradleProperties.length = 0;
  });

  afterEach(() => {
    delete process.env.EXPO_PUBLIC_APP_NAME;
    delete process.env.EXPO_PUBLIC_APP_ENV;
    delete process.env.EXPO_PUBLIC_API_BASE_URL;
    delete process.env.SUPABASE_URL;
    delete process.env.SUPABASE_ANON_KEY;
    delete process.env.SUPABASE_PASSWORD_RESET_REDIRECT_URL;
  });

  it('embeds runtime config defaults and normalizes kotlinVersion gradle property', () => {
    const getExpoConfig = loadExpoConfig();
    const config = getExpoConfig();

    expect(config.name).toBe('Template Repo Mobile Single');
    expect(config.extra).toEqual({
      appName: 'Template Repo Mobile Single',
      environment: 'development',
      apiBaseUrl: 'https://api.example.com',
      supabaseUrl: 'https://rregfrhtlmfktliijzpd.supabase.co',
      supabaseAnonKey: 'sb_publishable__1PnaWg4F91cxR3KFqQITA_TDMmdtLV',
      supabasePublishableKey: 'sb_publishable__1PnaWg4F91cxR3KFqQITA_TDMmdtLV',
      supabasePasswordResetRedirectUrl: 'pakiship://reset-password',
    });

    expect(mockAppliedGradleProperties).toEqual([
      [
        { type: 'property', key: 'kotlinVersion', value: '2.0.21' },
        { type: 'property', key: 'otherProperty', value: 'keep-me' },
      ],
      [
        { type: 'comment', value: '# generated by plugin' },
        { type: 'property', key: 'kotlinVersion', value: '2.0.21' },
      ],
    ]);
  });

  it('embeds environment overrides into Expo extra', () => {
    const getExpoConfig = loadExpoConfig();
    process.env.EXPO_PUBLIC_APP_NAME = 'Template Staging';
    process.env.EXPO_PUBLIC_APP_ENV = 'staging';
    process.env.EXPO_PUBLIC_API_BASE_URL = 'https://staging.api.example.com';
    process.env.SUPABASE_URL = 'https://staging-project.supabase.co';
    process.env.SUPABASE_ANON_KEY = 'staging-anon-key';
    process.env.SUPABASE_PASSWORD_RESET_REDIRECT_URL = 'pakiship://staging-reset';

    const config = getExpoConfig();

    expect(config.name).toBe('Template Staging');
    expect(config.extra).toEqual({
      appName: 'Template Staging',
      environment: 'staging',
      apiBaseUrl: 'https://staging.api.example.com',
      supabaseUrl: 'https://staging-project.supabase.co',
      supabaseAnonKey: 'staging-anon-key',
      supabasePublishableKey: 'staging-anon-key',
      supabasePasswordResetRedirectUrl: 'pakiship://staging-reset',
    });
  });
});
